version: "3"

services:
    nginx:
        image: nginx:1.23.2-alpine
        ports:
          - "8088:80"
        volumes:
          - ./nginx:/etc/nginx
        networks:
          - nginx

    rabbitmq:
         container_name: service-rabbitmq
         image: rabbitmq:3.11.1-management-alpine
         environment:
           - RABBITMQ_NODE_PORT=5672
           - RABBITMQ_DEFAULT_USER=user
           - RABBITMQ_DEFAULT_PASS=password
         ports:
           - 15672:15672
           - 5672:5672
         networks:
          - rabbitmq

networks:
  nginx:
    driver: bridge
    name: nginx
      
  rabbitmq:
    driver: bridge
    name: rabbitmq
